'use client'

import '@shopify/polaris/build/esm/styles.css'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import React from 'react'
import Layout from '@/components/layouts'
import { store } from '@/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Layout>
            {children}
          </Layout>
        </Provider>
      </body>
    </html>
  )
}
